server:
  root_url: https://grafana.platform.sphdigital.com.sg
auth.okta:
  name: Okta
  icon: okta
  enabled: ${grafana_okta_enabled}
  allow_sign_up: true
  client_id: ${GRAFANA_OAUTH_CLIENT_ID}
  client_secret: ${GRAFANA_OAUTH_CLIENT_SECRET}
  scopes: openid profile email groups
  auth_url: https://sphmedia.okta.com/oauth2/v1/authorize
  token_url: https://sphmedia.okta.com/oauth2/v1/token
  api_url: https://sphmedia.okta.com/oauth2/v1/userinfo
